#pragma once

#define HTTP_BODY_LIMIT_SMALL (8 * 1024)
#define HTTP_BODY_LIMIT_RESTORE (16 * 1024)

#ifndef PANEL_BRIGHTNESS_CAP_PERCENT
#define PANEL_BRIGHTNESS_CAP_PERCENT 100
#endif

#define BROWNOUT_BOOT_BRIGHTNESS_PERCENT 10
#define GIF_MIN_BYTES 13
