#pragma once

#ifndef MATRIXSIGN_STA_BOOT_TIMEOUT_MS
#define MATRIXSIGN_STA_BOOT_TIMEOUT_MS 15000
#endif

#ifndef MATRIXSIGN_STA_LOSS_RETRY_MS
#define MATRIXSIGN_STA_LOSS_RETRY_MS 120000
#endif

#ifndef MATRIXSIGN_AP_CHANNEL
#define MATRIXSIGN_AP_CHANNEL 6
#endif

#ifndef MATRIXSIGN_AP_MAX_CLIENTS
#define MATRIXSIGN_AP_MAX_CLIENTS 2
#endif

#ifndef MATRIXSIGN_RECOVERY_BRIGHTNESS
#define MATRIXSIGN_RECOVERY_BRIGHTNESS 5
#endif
